// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/ChatUserProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ChatServer.Common.Protobuf {

  /// <summary>Holder for reflection information generated from Proto/ChatUserProtocol.proto</summary>
  public static partial class ChatUserProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/ChatUserProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatUserProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxQcm90by9DaGF0VXNlclByb3RvY29sLnByb3RvEhpDaGF0U2VydmVyLkNv",
            "bW1vbi5Qcm90b2J1ZhogUHJvdG8vQ2hhdFJlbGF0aW9uUHJvdG9jb2wucHJv",
            "dG8aI1Byb3RvL0NoYXRDb21tdW5pY2F0ZVByb3RvY29sLnByb3RvGh1Qcm90",
            "by9DaGF0R3JvdXBQcm90b2NvbC5wcm90bxocUHJvdG8vQ2hhdEJhc2VQcm90",
            "b2NvbC5wcm90byIcCg5HZXRVc2VyUmVxdWVzdBIKCgJpZBgBIAEoCSK8AQoL",
            "VXNlck1lc3NhZ2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIOCgZpc01h",
            "bGUYAyABKAgSDQoFYmlydGgYBCABKAkSEAoIcGFzc3dvcmQYBSABKAkSFAoM",
            "aW50cm9kdWN0aW9uGAYgASgJEhEKCWhlYWRJbmRleBgHIAEoDRIRCgloZWFk",
            "Q291bnQYCCABKA0SFAoMcmVnaXN0ZXJUaW1lGAkgASgJEhAKCGlzT25saW5l",
            "GAogASgIIl4KFVVwZGF0ZVVzZXJEYXRhUmVxdWVzdBIOCgZ1c2VySWQYASAB",
            "KAkSNQoEdXNlchgCIAEoCzInLkNoYXRTZXJ2ZXIuQ29tbW9uLlByb3RvYnVm",
            "LlVzZXJNZXNzYWdlIl4KDlVwZGF0ZVVzZXJEYXRhEjwKCHJlc3BvbnNlGAEg",
            "ASgLMiouQ2hhdFNlcnZlci5Db21tb24uUHJvdG9idWYuQ29tbW9uUmVzcG9u",
            "c2USDgoGdXNlcklkGAIgASgJIiEKE0dldFVzZXJTYWZ0eVJlcXVlc3QSCgoC",
            "aWQYASABKAkiKQoFU2FmdHkSEAoIcXVlc3Rpb24YASABKAkSDgoGYW5zd2Vy",
            "GAIgASgJIk0KDFNhZnR5TWVzc2FnZRIKCgJpZBgBIAEoCRIxCgZzYWZ0eXMY",
            "AiADKAsyIS5DaGF0U2VydmVyLkNvbW1vbi5Qcm90b2J1Zi5TYWZ0eSJLCg9V",
            "cGRhdGVVc2VyU2FmdHkSOAoGc2FmdHlzGAEgASgLMiguQ2hhdFNlcnZlci5D",
            "b21tb24uUHJvdG9idWYuU2FmdHlNZXNzYWdlIjsKFU91dGxpbmVNZXNzYWdl",
            "UmVxdWVzdBIKCgJpZBgBIAEoCRIWCg5sYXN0TG9nb3V0VGltZRgCIAEoCSLA",
            "AQoURnJpZW5kUmVxdWVzdE1lc3NhZ2USEQoJcmVxdWVzdElkGAEgASgFEhIK",
            "CnVzZXJGcm9tSWQYAiABKAkSFAoMdXNlclRhcmdldElkGAMgASgJEg0KBWdy",
            "b3VwGAQgASgJEhMKC3JlcXVlc3RUaW1lGAUgASgJEhAKCGlzQWNjZXB0GAYg",
            "ASgIEhAKCGlzU29sdmVkGAcgASgIEhIKCnNvbHZlZFRpbWUYCCABKAkSDwoH",
            "bWVzc2FnZRgJIAEoCSLDAQoTR3JvdXBSZXF1ZXN0TWVzc2FnZRIRCglyZXF1",
            "ZXN0SWQYASABKAUSEgoKdXNlckZyb21JZBgCIAEoCRIPCgdncm91cElkGAMg",
            "ASgJEhMKC3JlcXVlc3RUaW1lGAQgASgJEhAKCGlzQWNjZXB0GAUgASgIEhAK",
            "CGlzU29sdmVkGAYgASgIEhIKCnNvbHZlZFRpbWUYByABKAkSDwoHbWVzc2Fn",
            "ZRgIIAEoCRIWCg5hY2NlcHRCeVVzZXJJZBgJIAEoCSLQBAoWT3V0bGluZU1l",
            "c3NhZ2VSZXNwb25zZRIKCgJpZBgBIAEoCRJICg5mcmllbmRSZXF1ZXN0cxgC",
            "IAMoCzIwLkNoYXRTZXJ2ZXIuQ29tbW9uLlByb3RvYnVmLkZyaWVuZFJlcXVl",
            "c3RNZXNzYWdlEkAKCm5ld0ZyaWVuZHMYAyADKAsyLC5DaGF0U2VydmVyLkNv",
            "bW1vbi5Qcm90b2J1Zi5OZXdGcmllbmRNZXNzYWdlEkIKC2ZyaWVuZENoYXRz",
            "GAQgAygLMi0uQ2hhdFNlcnZlci5Db21tb24uUHJvdG9idWYuRnJpZW5kQ2hh",
            "dE1lc3NhZ2USRgoNZnJpZW5kRGVsZXRlcxgFIAMoCzIvLkNoYXRTZXJ2ZXIu",
            "Q29tbW9uLlByb3RvYnVmLkZyaWVuZERlbGV0ZU1lc3NhZ2USQgoLZW50ZXJH",
            "cm91cHMYBiADKAsyLS5DaGF0U2VydmVyLkNvbW1vbi5Qcm90b2J1Zi5FbnRl",
            "ckdyb3VwTWVzc2FnZRJACgpncm91cENoYXRzGAcgAygLMiwuQ2hhdFNlcnZl",
            "ci5Db21tb24uUHJvdG9idWYuR3JvdXBDaGF0TWVzc2FnZRJGCg1ncm91cFJl",
            "cXVlc3RzGAggAygLMi8uQ2hhdFNlcnZlci5Db21tb24uUHJvdG9idWYuR3Jv",
            "dXBSZXF1ZXN0TWVzc2FnZRJECgxncm91cERlbGV0ZXMYCSADKAsyLi5DaGF0",
            "U2VydmVyLkNvbW1vbi5Qcm90b2J1Zi5Hcm91cERlbGV0ZU1lc3NhZ2ViBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ChatServer.Common.Protobuf.ChatRelationProtocolReflection.Descriptor, global::ChatServer.Common.Protobuf.ChatCommunicateProtocolReflection.Descriptor, global::ChatServer.Common.Protobuf.ChatGroupProtocolReflection.Descriptor, global::ChatServer.Common.Protobuf.ChatBaseProtocolReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.GetUserRequest), global::ChatServer.Common.Protobuf.GetUserRequest.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.UserMessage), global::ChatServer.Common.Protobuf.UserMessage.Parser, new[]{ "Id", "Name", "IsMale", "Birth", "Password", "Introduction", "HeadIndex", "HeadCount", "RegisterTime", "IsOnline" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.UpdateUserDataRequest), global::ChatServer.Common.Protobuf.UpdateUserDataRequest.Parser, new[]{ "UserId", "User" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.UpdateUserData), global::ChatServer.Common.Protobuf.UpdateUserData.Parser, new[]{ "Response", "UserId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.GetUserSaftyRequest), global::ChatServer.Common.Protobuf.GetUserSaftyRequest.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.Safty), global::ChatServer.Common.Protobuf.Safty.Parser, new[]{ "Question", "Answer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.SaftyMessage), global::ChatServer.Common.Protobuf.SaftyMessage.Parser, new[]{ "Id", "Saftys" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.UpdateUserSafty), global::ChatServer.Common.Protobuf.UpdateUserSafty.Parser, new[]{ "Saftys" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.OutlineMessageRequest), global::ChatServer.Common.Protobuf.OutlineMessageRequest.Parser, new[]{ "Id", "LastLogoutTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.FriendRequestMessage), global::ChatServer.Common.Protobuf.FriendRequestMessage.Parser, new[]{ "RequestId", "UserFromId", "UserTargetId", "Group", "RequestTime", "IsAccept", "IsSolved", "SolvedTime", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.GroupRequestMessage), global::ChatServer.Common.Protobuf.GroupRequestMessage.Parser, new[]{ "RequestId", "UserFromId", "GroupId", "RequestTime", "IsAccept", "IsSolved", "SolvedTime", "Message", "AcceptByUserId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Common.Protobuf.OutlineMessageResponse), global::ChatServer.Common.Protobuf.OutlineMessageResponse.Parser, new[]{ "Id", "FriendRequests", "NewFriends", "FriendChats", "FriendDeletes", "EnterGroups", "GroupChats", "GroupRequests", "GroupDeletes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 客户具体信息请求
  /// </summary>
  public sealed partial class GetUserRequest : pb::IMessage<GetUserRequest> {
    private static readonly pb::MessageParser<GetUserRequest> _parser = new pb::MessageParser<GetUserRequest>(() => new GetUserRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetUserRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserRequest(GetUserRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserRequest Clone() {
      return new GetUserRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetUserRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetUserRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetUserRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户具体信息
  /// </summary>
  public sealed partial class UserMessage : pb::IMessage<UserMessage> {
    private static readonly pb::MessageParser<UserMessage> _parser = new pb::MessageParser<UserMessage>(() => new UserMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserMessage(UserMessage other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      isMale_ = other.isMale_;
      birth_ = other.birth_;
      password_ = other.password_;
      introduction_ = other.introduction_;
      headIndex_ = other.headIndex_;
      headCount_ = other.headCount_;
      registerTime_ = other.registerTime_;
      isOnline_ = other.isOnline_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserMessage Clone() {
      return new UserMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isMale" field.</summary>
    public const int IsMaleFieldNumber = 3;
    private bool isMale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsMale {
      get { return isMale_; }
      set {
        isMale_ = value;
      }
    }

    /// <summary>Field number for the "birth" field.</summary>
    public const int BirthFieldNumber = 4;
    private string birth_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Birth {
      get { return birth_; }
      set {
        birth_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 5;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "introduction" field.</summary>
    public const int IntroductionFieldNumber = 6;
    private string introduction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Introduction {
      get { return introduction_; }
      set {
        introduction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "headIndex" field.</summary>
    public const int HeadIndexFieldNumber = 7;
    private uint headIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint HeadIndex {
      get { return headIndex_; }
      set {
        headIndex_ = value;
      }
    }

    /// <summary>Field number for the "headCount" field.</summary>
    public const int HeadCountFieldNumber = 8;
    private uint headCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint HeadCount {
      get { return headCount_; }
      set {
        headCount_ = value;
      }
    }

    /// <summary>Field number for the "registerTime" field.</summary>
    public const int RegisterTimeFieldNumber = 9;
    private string registerTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RegisterTime {
      get { return registerTime_; }
      set {
        registerTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isOnline" field.</summary>
    public const int IsOnlineFieldNumber = 10;
    private bool isOnline_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsOnline {
      get { return isOnline_; }
      set {
        isOnline_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (IsMale != other.IsMale) return false;
      if (Birth != other.Birth) return false;
      if (Password != other.Password) return false;
      if (Introduction != other.Introduction) return false;
      if (HeadIndex != other.HeadIndex) return false;
      if (HeadCount != other.HeadCount) return false;
      if (RegisterTime != other.RegisterTime) return false;
      if (IsOnline != other.IsOnline) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (IsMale != false) hash ^= IsMale.GetHashCode();
      if (Birth.Length != 0) hash ^= Birth.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Introduction.Length != 0) hash ^= Introduction.GetHashCode();
      if (HeadIndex != 0) hash ^= HeadIndex.GetHashCode();
      if (HeadCount != 0) hash ^= HeadCount.GetHashCode();
      if (RegisterTime.Length != 0) hash ^= RegisterTime.GetHashCode();
      if (IsOnline != false) hash ^= IsOnline.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (IsMale != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsMale);
      }
      if (Birth.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Birth);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Password);
      }
      if (Introduction.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Introduction);
      }
      if (HeadIndex != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(HeadIndex);
      }
      if (HeadCount != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(HeadCount);
      }
      if (RegisterTime.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(RegisterTime);
      }
      if (IsOnline != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsOnline);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (IsMale != false) {
        size += 1 + 1;
      }
      if (Birth.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Birth);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Introduction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Introduction);
      }
      if (HeadIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeadIndex);
      }
      if (HeadCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeadCount);
      }
      if (RegisterTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RegisterTime);
      }
      if (IsOnline != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.IsMale != false) {
        IsMale = other.IsMale;
      }
      if (other.Birth.Length != 0) {
        Birth = other.Birth;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Introduction.Length != 0) {
        Introduction = other.Introduction;
      }
      if (other.HeadIndex != 0) {
        HeadIndex = other.HeadIndex;
      }
      if (other.HeadCount != 0) {
        HeadCount = other.HeadCount;
      }
      if (other.RegisterTime.Length != 0) {
        RegisterTime = other.RegisterTime;
      }
      if (other.IsOnline != false) {
        IsOnline = other.IsOnline;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            IsMale = input.ReadBool();
            break;
          }
          case 34: {
            Birth = input.ReadString();
            break;
          }
          case 42: {
            Password = input.ReadString();
            break;
          }
          case 50: {
            Introduction = input.ReadString();
            break;
          }
          case 56: {
            HeadIndex = input.ReadUInt32();
            break;
          }
          case 64: {
            HeadCount = input.ReadUInt32();
            break;
          }
          case 74: {
            RegisterTime = input.ReadString();
            break;
          }
          case 80: {
            IsOnline = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户具体信息更新
  /// </summary>
  public sealed partial class UpdateUserDataRequest : pb::IMessage<UpdateUserDataRequest> {
    private static readonly pb::MessageParser<UpdateUserDataRequest> _parser = new pb::MessageParser<UpdateUserDataRequest>(() => new UpdateUserDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateUserDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserDataRequest(UpdateUserDataRequest other) : this() {
      userId_ = other.userId_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserDataRequest Clone() {
      return new UpdateUserDataRequest(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private global::ChatServer.Common.Protobuf.UserMessage user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Common.Protobuf.UserMessage User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateUserDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateUserDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (!object.Equals(User, other.User)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateUserDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::ChatServer.Common.Protobuf.UserMessage();
        }
        User.MergeFrom(other.User);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::ChatServer.Common.Protobuf.UserMessage();
            }
            input.ReadMessage(User);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateUserData : pb::IMessage<UpdateUserData> {
    private static readonly pb::MessageParser<UpdateUserData> _parser = new pb::MessageParser<UpdateUserData>(() => new UpdateUserData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateUserData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserData(UpdateUserData other) : this() {
      response_ = other.response_ != null ? other.response_.Clone() : null;
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserData Clone() {
      return new UpdateUserData(this);
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 1;
    private global::ChatServer.Common.Protobuf.CommonResponse response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Common.Protobuf.CommonResponse Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 2;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateUserData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateUserData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Response, other.Response)) return false;
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (response_ != null) hash ^= Response.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (response_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Response);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateUserData other) {
      if (other == null) {
        return;
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::ChatServer.Common.Protobuf.CommonResponse();
        }
        Response.MergeFrom(other.Response);
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (response_ == null) {
              Response = new global::ChatServer.Common.Protobuf.CommonResponse();
            }
            input.ReadMessage(Response);
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户安全信息请求
  /// </summary>
  public sealed partial class GetUserSaftyRequest : pb::IMessage<GetUserSaftyRequest> {
    private static readonly pb::MessageParser<GetUserSaftyRequest> _parser = new pb::MessageParser<GetUserSaftyRequest>(() => new GetUserSaftyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetUserSaftyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSaftyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSaftyRequest(GetUserSaftyRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSaftyRequest Clone() {
      return new GetUserSaftyRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetUserSaftyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetUserSaftyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetUserSaftyRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 安全信息
  /// </summary>
  public sealed partial class Safty : pb::IMessage<Safty> {
    private static readonly pb::MessageParser<Safty> _parser = new pb::MessageParser<Safty>(() => new Safty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Safty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Safty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Safty(Safty other) : this() {
      question_ = other.question_;
      answer_ = other.answer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Safty Clone() {
      return new Safty(this);
    }

    /// <summary>Field number for the "question" field.</summary>
    public const int QuestionFieldNumber = 1;
    private string question_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Question {
      get { return question_; }
      set {
        question_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "answer" field.</summary>
    public const int AnswerFieldNumber = 2;
    private string answer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Answer {
      get { return answer_; }
      set {
        answer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Safty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Safty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Question != other.Question) return false;
      if (Answer != other.Answer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Question.Length != 0) hash ^= Question.GetHashCode();
      if (Answer.Length != 0) hash ^= Answer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Question.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Question);
      }
      if (Answer.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Answer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Question.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Question);
      }
      if (Answer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Answer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Safty other) {
      if (other == null) {
        return;
      }
      if (other.Question.Length != 0) {
        Question = other.Question;
      }
      if (other.Answer.Length != 0) {
        Answer = other.Answer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Question = input.ReadString();
            break;
          }
          case 18: {
            Answer = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户安全信息
  /// </summary>
  public sealed partial class SaftyMessage : pb::IMessage<SaftyMessage> {
    private static readonly pb::MessageParser<SaftyMessage> _parser = new pb::MessageParser<SaftyMessage>(() => new SaftyMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SaftyMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaftyMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaftyMessage(SaftyMessage other) : this() {
      id_ = other.id_;
      saftys_ = other.saftys_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaftyMessage Clone() {
      return new SaftyMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "saftys" field.</summary>
    public const int SaftysFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.Safty> _repeated_saftys_codec
        = pb::FieldCodec.ForMessage(18, global::ChatServer.Common.Protobuf.Safty.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.Safty> saftys_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.Safty>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.Safty> Saftys {
      get { return saftys_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SaftyMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SaftyMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!saftys_.Equals(other.saftys_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= saftys_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      saftys_.WriteTo(output, _repeated_saftys_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += saftys_.CalculateSize(_repeated_saftys_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SaftyMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      saftys_.Add(other.saftys_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            saftys_.AddEntriesFrom(input, _repeated_saftys_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户安全信息更新
  /// </summary>
  public sealed partial class UpdateUserSafty : pb::IMessage<UpdateUserSafty> {
    private static readonly pb::MessageParser<UpdateUserSafty> _parser = new pb::MessageParser<UpdateUserSafty>(() => new UpdateUserSafty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateUserSafty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSafty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSafty(UpdateUserSafty other) : this() {
      saftys_ = other.saftys_ != null ? other.saftys_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSafty Clone() {
      return new UpdateUserSafty(this);
    }

    /// <summary>Field number for the "saftys" field.</summary>
    public const int SaftysFieldNumber = 1;
    private global::ChatServer.Common.Protobuf.SaftyMessage saftys_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Common.Protobuf.SaftyMessage Saftys {
      get { return saftys_; }
      set {
        saftys_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateUserSafty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateUserSafty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Saftys, other.Saftys)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (saftys_ != null) hash ^= Saftys.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (saftys_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Saftys);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (saftys_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Saftys);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateUserSafty other) {
      if (other == null) {
        return;
      }
      if (other.saftys_ != null) {
        if (saftys_ == null) {
          Saftys = new global::ChatServer.Common.Protobuf.SaftyMessage();
        }
        Saftys.MergeFrom(other.Saftys);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (saftys_ == null) {
              Saftys = new global::ChatServer.Common.Protobuf.SaftyMessage();
            }
            input.ReadMessage(Saftys);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// -------------------------------------- //
  /// </summary>
  public sealed partial class OutlineMessageRequest : pb::IMessage<OutlineMessageRequest> {
    private static readonly pb::MessageParser<OutlineMessageRequest> _parser = new pb::MessageParser<OutlineMessageRequest>(() => new OutlineMessageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutlineMessageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutlineMessageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutlineMessageRequest(OutlineMessageRequest other) : this() {
      id_ = other.id_;
      lastLogoutTime_ = other.lastLogoutTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutlineMessageRequest Clone() {
      return new OutlineMessageRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastLogoutTime" field.</summary>
    public const int LastLogoutTimeFieldNumber = 2;
    private string lastLogoutTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastLogoutTime {
      get { return lastLogoutTime_; }
      set {
        lastLogoutTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutlineMessageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutlineMessageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (LastLogoutTime != other.LastLogoutTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (LastLogoutTime.Length != 0) hash ^= LastLogoutTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (LastLogoutTime.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastLogoutTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (LastLogoutTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastLogoutTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutlineMessageRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.LastLogoutTime.Length != 0) {
        LastLogoutTime = other.LastLogoutTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            LastLogoutTime = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FriendRequestMessage : pb::IMessage<FriendRequestMessage> {
    private static readonly pb::MessageParser<FriendRequestMessage> _parser = new pb::MessageParser<FriendRequestMessage>(() => new FriendRequestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FriendRequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendRequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendRequestMessage(FriendRequestMessage other) : this() {
      requestId_ = other.requestId_;
      userFromId_ = other.userFromId_;
      userTargetId_ = other.userTargetId_;
      group_ = other.group_;
      requestTime_ = other.requestTime_;
      isAccept_ = other.isAccept_;
      isSolved_ = other.isSolved_;
      solvedTime_ = other.solvedTime_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendRequestMessage Clone() {
      return new FriendRequestMessage(this);
    }

    /// <summary>Field number for the "requestId" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private int requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "userFromId" field.</summary>
    public const int UserFromIdFieldNumber = 2;
    private string userFromId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserFromId {
      get { return userFromId_; }
      set {
        userFromId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userTargetId" field.</summary>
    public const int UserTargetIdFieldNumber = 3;
    private string userTargetId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserTargetId {
      get { return userTargetId_; }
      set {
        userTargetId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "group" field.</summary>
    public const int GroupFieldNumber = 4;
    private string group_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Group {
      get { return group_; }
      set {
        group_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "requestTime" field.</summary>
    public const int RequestTimeFieldNumber = 5;
    private string requestTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestTime {
      get { return requestTime_; }
      set {
        requestTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isAccept" field.</summary>
    public const int IsAcceptFieldNumber = 6;
    private bool isAccept_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAccept {
      get { return isAccept_; }
      set {
        isAccept_ = value;
      }
    }

    /// <summary>Field number for the "isSolved" field.</summary>
    public const int IsSolvedFieldNumber = 7;
    private bool isSolved_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsSolved {
      get { return isSolved_; }
      set {
        isSolved_ = value;
      }
    }

    /// <summary>Field number for the "solvedTime" field.</summary>
    public const int SolvedTimeFieldNumber = 8;
    private string solvedTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SolvedTime {
      get { return solvedTime_; }
      set {
        solvedTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 9;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FriendRequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FriendRequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      if (UserFromId != other.UserFromId) return false;
      if (UserTargetId != other.UserTargetId) return false;
      if (Group != other.Group) return false;
      if (RequestTime != other.RequestTime) return false;
      if (IsAccept != other.IsAccept) return false;
      if (IsSolved != other.IsSolved) return false;
      if (SolvedTime != other.SolvedTime) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId != 0) hash ^= RequestId.GetHashCode();
      if (UserFromId.Length != 0) hash ^= UserFromId.GetHashCode();
      if (UserTargetId.Length != 0) hash ^= UserTargetId.GetHashCode();
      if (Group.Length != 0) hash ^= Group.GetHashCode();
      if (RequestTime.Length != 0) hash ^= RequestTime.GetHashCode();
      if (IsAccept != false) hash ^= IsAccept.GetHashCode();
      if (IsSolved != false) hash ^= IsSolved.GetHashCode();
      if (SolvedTime.Length != 0) hash ^= SolvedTime.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestId);
      }
      if (UserFromId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserFromId);
      }
      if (UserTargetId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserTargetId);
      }
      if (Group.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Group);
      }
      if (RequestTime.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(RequestTime);
      }
      if (IsAccept != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsAccept);
      }
      if (IsSolved != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsSolved);
      }
      if (SolvedTime.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(SolvedTime);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequestId);
      }
      if (UserFromId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserFromId);
      }
      if (UserTargetId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserTargetId);
      }
      if (Group.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Group);
      }
      if (RequestTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestTime);
      }
      if (IsAccept != false) {
        size += 1 + 1;
      }
      if (IsSolved != false) {
        size += 1 + 1;
      }
      if (SolvedTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SolvedTime);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FriendRequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.RequestId != 0) {
        RequestId = other.RequestId;
      }
      if (other.UserFromId.Length != 0) {
        UserFromId = other.UserFromId;
      }
      if (other.UserTargetId.Length != 0) {
        UserTargetId = other.UserTargetId;
      }
      if (other.Group.Length != 0) {
        Group = other.Group;
      }
      if (other.RequestTime.Length != 0) {
        RequestTime = other.RequestTime;
      }
      if (other.IsAccept != false) {
        IsAccept = other.IsAccept;
      }
      if (other.IsSolved != false) {
        IsSolved = other.IsSolved;
      }
      if (other.SolvedTime.Length != 0) {
        SolvedTime = other.SolvedTime;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestId = input.ReadInt32();
            break;
          }
          case 18: {
            UserFromId = input.ReadString();
            break;
          }
          case 26: {
            UserTargetId = input.ReadString();
            break;
          }
          case 34: {
            Group = input.ReadString();
            break;
          }
          case 42: {
            RequestTime = input.ReadString();
            break;
          }
          case 48: {
            IsAccept = input.ReadBool();
            break;
          }
          case 56: {
            IsSolved = input.ReadBool();
            break;
          }
          case 66: {
            SolvedTime = input.ReadString();
            break;
          }
          case 74: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GroupRequestMessage : pb::IMessage<GroupRequestMessage> {
    private static readonly pb::MessageParser<GroupRequestMessage> _parser = new pb::MessageParser<GroupRequestMessage>(() => new GroupRequestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GroupRequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupRequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupRequestMessage(GroupRequestMessage other) : this() {
      requestId_ = other.requestId_;
      userFromId_ = other.userFromId_;
      groupId_ = other.groupId_;
      requestTime_ = other.requestTime_;
      isAccept_ = other.isAccept_;
      isSolved_ = other.isSolved_;
      solvedTime_ = other.solvedTime_;
      message_ = other.message_;
      acceptByUserId_ = other.acceptByUserId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupRequestMessage Clone() {
      return new GroupRequestMessage(this);
    }

    /// <summary>Field number for the "requestId" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private int requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "userFromId" field.</summary>
    public const int UserFromIdFieldNumber = 2;
    private string userFromId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserFromId {
      get { return userFromId_; }
      set {
        userFromId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "groupId" field.</summary>
    public const int GroupIdFieldNumber = 3;
    private string groupId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GroupId {
      get { return groupId_; }
      set {
        groupId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "requestTime" field.</summary>
    public const int RequestTimeFieldNumber = 4;
    private string requestTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestTime {
      get { return requestTime_; }
      set {
        requestTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isAccept" field.</summary>
    public const int IsAcceptFieldNumber = 5;
    private bool isAccept_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAccept {
      get { return isAccept_; }
      set {
        isAccept_ = value;
      }
    }

    /// <summary>Field number for the "isSolved" field.</summary>
    public const int IsSolvedFieldNumber = 6;
    private bool isSolved_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsSolved {
      get { return isSolved_; }
      set {
        isSolved_ = value;
      }
    }

    /// <summary>Field number for the "solvedTime" field.</summary>
    public const int SolvedTimeFieldNumber = 7;
    private string solvedTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SolvedTime {
      get { return solvedTime_; }
      set {
        solvedTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 8;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "acceptByUserId" field.</summary>
    public const int AcceptByUserIdFieldNumber = 9;
    private string acceptByUserId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AcceptByUserId {
      get { return acceptByUserId_; }
      set {
        acceptByUserId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GroupRequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GroupRequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      if (UserFromId != other.UserFromId) return false;
      if (GroupId != other.GroupId) return false;
      if (RequestTime != other.RequestTime) return false;
      if (IsAccept != other.IsAccept) return false;
      if (IsSolved != other.IsSolved) return false;
      if (SolvedTime != other.SolvedTime) return false;
      if (Message != other.Message) return false;
      if (AcceptByUserId != other.AcceptByUserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId != 0) hash ^= RequestId.GetHashCode();
      if (UserFromId.Length != 0) hash ^= UserFromId.GetHashCode();
      if (GroupId.Length != 0) hash ^= GroupId.GetHashCode();
      if (RequestTime.Length != 0) hash ^= RequestTime.GetHashCode();
      if (IsAccept != false) hash ^= IsAccept.GetHashCode();
      if (IsSolved != false) hash ^= IsSolved.GetHashCode();
      if (SolvedTime.Length != 0) hash ^= SolvedTime.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (AcceptByUserId.Length != 0) hash ^= AcceptByUserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestId);
      }
      if (UserFromId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserFromId);
      }
      if (GroupId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GroupId);
      }
      if (RequestTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RequestTime);
      }
      if (IsAccept != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsAccept);
      }
      if (IsSolved != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsSolved);
      }
      if (SolvedTime.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SolvedTime);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Message);
      }
      if (AcceptByUserId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AcceptByUserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequestId);
      }
      if (UserFromId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserFromId);
      }
      if (GroupId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupId);
      }
      if (RequestTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestTime);
      }
      if (IsAccept != false) {
        size += 1 + 1;
      }
      if (IsSolved != false) {
        size += 1 + 1;
      }
      if (SolvedTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SolvedTime);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (AcceptByUserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AcceptByUserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GroupRequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.RequestId != 0) {
        RequestId = other.RequestId;
      }
      if (other.UserFromId.Length != 0) {
        UserFromId = other.UserFromId;
      }
      if (other.GroupId.Length != 0) {
        GroupId = other.GroupId;
      }
      if (other.RequestTime.Length != 0) {
        RequestTime = other.RequestTime;
      }
      if (other.IsAccept != false) {
        IsAccept = other.IsAccept;
      }
      if (other.IsSolved != false) {
        IsSolved = other.IsSolved;
      }
      if (other.SolvedTime.Length != 0) {
        SolvedTime = other.SolvedTime;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.AcceptByUserId.Length != 0) {
        AcceptByUserId = other.AcceptByUserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestId = input.ReadInt32();
            break;
          }
          case 18: {
            UserFromId = input.ReadString();
            break;
          }
          case 26: {
            GroupId = input.ReadString();
            break;
          }
          case 34: {
            RequestTime = input.ReadString();
            break;
          }
          case 40: {
            IsAccept = input.ReadBool();
            break;
          }
          case 48: {
            IsSolved = input.ReadBool();
            break;
          }
          case 58: {
            SolvedTime = input.ReadString();
            break;
          }
          case 66: {
            Message = input.ReadString();
            break;
          }
          case 74: {
            AcceptByUserId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OutlineMessageResponse : pb::IMessage<OutlineMessageResponse> {
    private static readonly pb::MessageParser<OutlineMessageResponse> _parser = new pb::MessageParser<OutlineMessageResponse>(() => new OutlineMessageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutlineMessageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Common.Protobuf.ChatUserProtocolReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutlineMessageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutlineMessageResponse(OutlineMessageResponse other) : this() {
      id_ = other.id_;
      friendRequests_ = other.friendRequests_.Clone();
      newFriends_ = other.newFriends_.Clone();
      friendChats_ = other.friendChats_.Clone();
      friendDeletes_ = other.friendDeletes_.Clone();
      enterGroups_ = other.enterGroups_.Clone();
      groupChats_ = other.groupChats_.Clone();
      groupRequests_ = other.groupRequests_.Clone();
      groupDeletes_ = other.groupDeletes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutlineMessageResponse Clone() {
      return new OutlineMessageResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "friendRequests" field.</summary>
    public const int FriendRequestsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.FriendRequestMessage> _repeated_friendRequests_codec
        = pb::FieldCodec.ForMessage(18, global::ChatServer.Common.Protobuf.FriendRequestMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendRequestMessage> friendRequests_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendRequestMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendRequestMessage> FriendRequests {
      get { return friendRequests_; }
    }

    /// <summary>Field number for the "newFriends" field.</summary>
    public const int NewFriendsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.NewFriendMessage> _repeated_newFriends_codec
        = pb::FieldCodec.ForMessage(26, global::ChatServer.Common.Protobuf.NewFriendMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.NewFriendMessage> newFriends_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.NewFriendMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.NewFriendMessage> NewFriends {
      get { return newFriends_; }
    }

    /// <summary>Field number for the "friendChats" field.</summary>
    public const int FriendChatsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.FriendChatMessage> _repeated_friendChats_codec
        = pb::FieldCodec.ForMessage(34, global::ChatServer.Common.Protobuf.FriendChatMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendChatMessage> friendChats_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendChatMessage> FriendChats {
      get { return friendChats_; }
    }

    /// <summary>Field number for the "friendDeletes" field.</summary>
    public const int FriendDeletesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.FriendDeleteMessage> _repeated_friendDeletes_codec
        = pb::FieldCodec.ForMessage(42, global::ChatServer.Common.Protobuf.FriendDeleteMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendDeleteMessage> friendDeletes_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendDeleteMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.FriendDeleteMessage> FriendDeletes {
      get { return friendDeletes_; }
    }

    /// <summary>Field number for the "enterGroups" field.</summary>
    public const int EnterGroupsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.EnterGroupMessage> _repeated_enterGroups_codec
        = pb::FieldCodec.ForMessage(50, global::ChatServer.Common.Protobuf.EnterGroupMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.EnterGroupMessage> enterGroups_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.EnterGroupMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.EnterGroupMessage> EnterGroups {
      get { return enterGroups_; }
    }

    /// <summary>Field number for the "groupChats" field.</summary>
    public const int GroupChatsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.GroupChatMessage> _repeated_groupChats_codec
        = pb::FieldCodec.ForMessage(58, global::ChatServer.Common.Protobuf.GroupChatMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupChatMessage> groupChats_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupChatMessage> GroupChats {
      get { return groupChats_; }
    }

    /// <summary>Field number for the "groupRequests" field.</summary>
    public const int GroupRequestsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.GroupRequestMessage> _repeated_groupRequests_codec
        = pb::FieldCodec.ForMessage(66, global::ChatServer.Common.Protobuf.GroupRequestMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupRequestMessage> groupRequests_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupRequestMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupRequestMessage> GroupRequests {
      get { return groupRequests_; }
    }

    /// <summary>Field number for the "groupDeletes" field.</summary>
    public const int GroupDeletesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::ChatServer.Common.Protobuf.GroupDeleteMessage> _repeated_groupDeletes_codec
        = pb::FieldCodec.ForMessage(74, global::ChatServer.Common.Protobuf.GroupDeleteMessage.Parser);
    private readonly pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupDeleteMessage> groupDeletes_ = new pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupDeleteMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ChatServer.Common.Protobuf.GroupDeleteMessage> GroupDeletes {
      get { return groupDeletes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutlineMessageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutlineMessageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!friendRequests_.Equals(other.friendRequests_)) return false;
      if(!newFriends_.Equals(other.newFriends_)) return false;
      if(!friendChats_.Equals(other.friendChats_)) return false;
      if(!friendDeletes_.Equals(other.friendDeletes_)) return false;
      if(!enterGroups_.Equals(other.enterGroups_)) return false;
      if(!groupChats_.Equals(other.groupChats_)) return false;
      if(!groupRequests_.Equals(other.groupRequests_)) return false;
      if(!groupDeletes_.Equals(other.groupDeletes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= friendRequests_.GetHashCode();
      hash ^= newFriends_.GetHashCode();
      hash ^= friendChats_.GetHashCode();
      hash ^= friendDeletes_.GetHashCode();
      hash ^= enterGroups_.GetHashCode();
      hash ^= groupChats_.GetHashCode();
      hash ^= groupRequests_.GetHashCode();
      hash ^= groupDeletes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      friendRequests_.WriteTo(output, _repeated_friendRequests_codec);
      newFriends_.WriteTo(output, _repeated_newFriends_codec);
      friendChats_.WriteTo(output, _repeated_friendChats_codec);
      friendDeletes_.WriteTo(output, _repeated_friendDeletes_codec);
      enterGroups_.WriteTo(output, _repeated_enterGroups_codec);
      groupChats_.WriteTo(output, _repeated_groupChats_codec);
      groupRequests_.WriteTo(output, _repeated_groupRequests_codec);
      groupDeletes_.WriteTo(output, _repeated_groupDeletes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += friendRequests_.CalculateSize(_repeated_friendRequests_codec);
      size += newFriends_.CalculateSize(_repeated_newFriends_codec);
      size += friendChats_.CalculateSize(_repeated_friendChats_codec);
      size += friendDeletes_.CalculateSize(_repeated_friendDeletes_codec);
      size += enterGroups_.CalculateSize(_repeated_enterGroups_codec);
      size += groupChats_.CalculateSize(_repeated_groupChats_codec);
      size += groupRequests_.CalculateSize(_repeated_groupRequests_codec);
      size += groupDeletes_.CalculateSize(_repeated_groupDeletes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutlineMessageResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      friendRequests_.Add(other.friendRequests_);
      newFriends_.Add(other.newFriends_);
      friendChats_.Add(other.friendChats_);
      friendDeletes_.Add(other.friendDeletes_);
      enterGroups_.Add(other.enterGroups_);
      groupChats_.Add(other.groupChats_);
      groupRequests_.Add(other.groupRequests_);
      groupDeletes_.Add(other.groupDeletes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            friendRequests_.AddEntriesFrom(input, _repeated_friendRequests_codec);
            break;
          }
          case 26: {
            newFriends_.AddEntriesFrom(input, _repeated_newFriends_codec);
            break;
          }
          case 34: {
            friendChats_.AddEntriesFrom(input, _repeated_friendChats_codec);
            break;
          }
          case 42: {
            friendDeletes_.AddEntriesFrom(input, _repeated_friendDeletes_codec);
            break;
          }
          case 50: {
            enterGroups_.AddEntriesFrom(input, _repeated_enterGroups_codec);
            break;
          }
          case 58: {
            groupChats_.AddEntriesFrom(input, _repeated_groupChats_codec);
            break;
          }
          case 66: {
            groupRequests_.AddEntriesFrom(input, _repeated_groupRequests_codec);
            break;
          }
          case 74: {
            groupDeletes_.AddEntriesFrom(input, _repeated_groupDeletes_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
